name: cd

on:
  push:
    branches: main

jobs:
  deploy_to_heroku:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build, Push and Deploy to Heroku #set the whatever name you want to this step
        id: heroku
        uses: jctaveras/heroku-deploy@v2.0.0
        with:
        email: ${{ secrets.HEROKU_EMAIL }}
        api_key: ${{ secrets.HEROKU_API_KEY }}
        app_name: ${{ secrets.HEROKU_APP_NAME }}
        dockerfile_path: './dockerfile'