name: Tests

on:
  push:

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Getting files from GitHub
      uses: actions/checkout@v1
    - name: Configuring Ruby 2.6
      uses: ruby/setup-ruby@v1.47.0
      with:
        bundler-cache: true
        ruby-version: 2.6
    - name: Checking Ruby version
      run: |
        ruby -v
    - name: Test with Rake
      run: |
        bundle install --jobs 4 --retry 3
        bundle exec rake -t
